In [1]:
import pandas as pd
import pandas as pd
from pandasql import sqldf

In [5]:
users = pd.read_csv("Updated_Datasets/USER_CLEANED.csv")
transactions = pd.read_csv("Updated_Datasets/TRANSACTION_CLEANED.csv")
products = pd.read_csv("Updated_Datasets/PRODUCTS_CLEANED.csv")

In [10]:
products.head()

,CATEGORY_1,CATEGORY_2,CATEGORY_3,CATEGORY_4,MANUFACTURER,BRAND,BARCODE
0,Health & Wellness,Sexual Health,Conductivity Gels & Lotions,NaN,NaN,NaN,796494407820.0
1,Snacks,Puffed Snacks,Cheese Curls & Puffs,NaN,NaN,NaN,023278011028.0
2,Health & Wellness,Hair Care,Hair Care Accessories,NaN,PLACEHOLDER MANUFACTURER,ELECSOP,461817824225.0
3,Health & Wellness,Oral Care,Toothpaste,NaN,COLGATE-PALMOLIVE,COLGATE,035000466815.0
4,Health & Wellness,Medicines & Treatments,Essential Oils,NaN,MAPLE HOLISTICS AND HONEYDEW PRODUCTS INTERCHA...,MAPLE HOLISTICS,806810850459.0

In [6]:
def pysqldf(q):
    return sqldf(q, globals())

In [11]:
# SQL query to find the top 5 brands by receipts scanned among users 21 and over
query = """
SELECT p.BRAND, COUNT(DISTINCT t.RECEIPT_ID) AS receipt_count
FROM users u
JOIN transactions t ON u.ID = t.USER_ID
JOIN products p ON t.BARCODE = p.BARCODE
WHERE u.AGE >= 21
GROUP BY p.BRAND
ORDER BY receipt_count DESC
LIMIT 5;
"""

# Execute the query
top_5_brands_by_receipts = pysqldf(query)
print(top_5_brands_by_receipts)

             BRAND  receipt_count
0      NERDS CANDY              3
1             DOVE              3
2             None              3
3          TRIDENT              2
4  SOUR PATCH KIDS              2

In [9]:
query = """
SELECT t.*, p.*
FROM transactions t
JOIN products p ON t.BARCODE = p.BARCODE;
"""

# Execute the query
joined_data = pysqldf(query)
print(joined_data)

                                 RECEIPT_ID PURCHASE_DATE  \
0      7b3ec72d-9d30-40b8-b185-0bfb638942a9    2024-08-20
1      04869b68-29e3-4e8d-9bdb-950046fc3473    2024-08-05
2      7ee1798e-fd2e-4278-838b-f417fdcafe08    2024-08-30
3      30977cbc-1d29-4f2d-851c-1104432769d0    2024-09-01
4      48c7720b-7097-4cee-995e-721e52c623bd    2024-06-25
...                                     ...           ...
12422  443b2c20-78c3-4cc5-b12d-9cdc07e8ee9d    2024-08-09
12423  f6d3e61d-488d-448b-8148-8d681e55b3d2    2024-09-01
12424  e1b2f634-c9ad-4152-b662-4b22efc25862    2024-08-11
12425  b07ef8dd-e444-40a2-819b-f74a3e5f1ae7    2024-07-11
12426  3a179c4e-46f2-4126-b3d2-3514afc23a3e    2024-08-07

                     SCAN_DATE            STORE_NAME  \
0      2024-08-20 11:17:29.633  DOLLAR GENERAL STORE
1      2024-08-09 16:06:00.570  DOLLAR GENERAL STORE
2      2024-09-04 12:53:31.478  DOLLAR GENERAL STORE
3      2024-09-01 09:40:16.103               WALMART
4      2024-06-25 17:56:43.654                COSTCO
...                        ...                   ...
12422  2024-08-09 15:27:12.423             SHOP RITE
12423  2024-09-06 08:03:54.617                TARGET
12424  2024-08-11 18:15:56.736           STOP & SHOP
12425  2024-07-11 08:03:25.816               WALMART
12426  2024-08-07 15:30:07.911               WALMART

                        USER_ID         BARCODE  FINAL_QUANTITY  FINAL_SALE  \
0      60fc1e6deb7585430ff52ee7  745527114884.0             1.0        1.65
1      654cf234a225ea102b81072e  745527114884.0             1.0        1.65
2      65c29b137050d0a6206cd24f  012000504051.0             1.0        5.25
3      5baf733455206419c416c3be  037000779704.0             1.0        2.20
4      65c5b9a416cc39173210ae15  000009697867.0             1.0        9.69
...                         ...             ...             ...         ...
12422  61a3a94b6f1d182a23c8a255  041780073808.0             1.0        3.00
12423  61056fcc1efef449f0f39f7c  085239042663.0             1.0        3.46
12424  60aa809f188b926b2244c974  046100400555.0             1.0        2.00
12425  60bd26e83dc3b13a15c5f4e7  646630019670.0             1.0       20.96
12426  64e94d64ca929250373ef6e1  307660745853.0             1.0        5.48

              CATEGORY_1              CATEGORY_2  \
0                 Snacks                 Cookies
1                 Snacks                 Cookies
2              Beverages  Carbonated Soft Drinks
3      Health & Wellness               Oral Care
4                 Snacks                 Cookies
...                  ...                     ...
12422             Snacks                Pretzels
12423             Snacks                   Chips
12424              Dairy                  Cheese
12425  Health & Wellness               Hair Care
12426  Health & Wellness  Medicines & Treatments

                                    CATEGORY_3  \
0                                         None
1                                         None
2                                         Cola
3                                   Toothpaste
4                                         None
...                                        ...
12422                         Covered Pretzels
12423                           Tortilla Chips
12424                 Shredded & Grated Cheese
12425                    Hair Styling Products
12426  Digestive Health Medicines & Treatments

                                        CATEGORY_4            MANUFACTURER  \
0                                             None          DOLLAR GENERAL
1                                             None          DOLLAR GENERAL
2                                     Regular Cola                 PEPSICO
3                                             None        PROCTER & GAMBLE
4                                             None       MEIJI AMERICA INC
...                                            ...                     ...
12422                                         None  UTZ QUALITY FOODS, LLC
12423                                         None      TARGET CORPORATION
12424                                         None                SARGENTO
12425                                         None                  HENKEL
12426  Heartburn & Antacids Medicines & Treatments                  HALEON

               BRAND         BARCODE
0      CLOVER VALLEY  745527114884.0
1      CLOVER VALLEY  745527114884.0
2              PEPSI  012000504051.0
3              CREST  037000779704.0
4        HELLO PANDA  000009697867.0
...              ...             ...
12422            UTZ  041780073808.0
12423  GOOD & GATHER  085239042663.0
12424       SARGENTO  046100400555.0
12425       SEXYHAIR  646630019670.0
12426           TUMS  307660745853.0

[12427 rows x 15 columns]